env:
  render_size: 400
  paddle_width: 0.2
  paddle_speed: 0.03
  max_score: 3
  enable_render: false
  enable_spin: true
  magnus_factor: 0.015
  restitution: 1
  friction: 0.6
  ball_mass: 1.0
  world_ball_radius: 0.03
  ball_speed_range: [0.03, 0.05]
  spin_range: [-5, 5]
  ball_angle_intervals: [[-60, -30], [30, 60]]
  speed_scale_every: 1
  speed_increment: 0.1

training:
  max_generations: 8
  episodes_per_generation: 2000       # ↑ 更多训练样本
  eval_episodes: 300                 # ↑ 更大评估样本减少波动
  max_retries_for_generation: 16
  win_rate_interval: 200             # ↑ 平滑训练统计
  target_update_interval: 1000
  model_id: 5
  opponent_pool_ratio: 0.3
  min_pool_generation: 2

  # 升级条件：调低对 A 门槛，调高对 Pool 门槛
  curr_win_threshold: 0.68
  pool_win_threshold: 0.65

  lr: 0.00025                        # ↓ 更小学习率，训练更平稳
  gamma: 0.99
  batch_size: 256                   # ↑ 更大批量，梯度更稳定
  memory_size: 1000000              # ↑ 回放容量
  epsilon_decay: 0.995              # ↑ 探索衰减慢一些
  min_epsilon: 0.02                 # ↓ 更低后期随机率

  init_model_path: "checkpoints/model4-12.pth"
