env:
  render_size: 400
  paddle_width: 0.2
  paddle_speed: 0.03
  max_score: 3
  enable_render: false

  # 馬格努斯 + 剛體參數
  enable_spin: true
  magnus_factor: 0.015
  restitution: 1
  friction: 0.6
  ball_mass: 1.0
  world_ball_radius: 0.03

  # 初始條件
  ball_speed_range: [0.03, 0.05]
  spin_range: [-5, 5]
  ball_angle_intervals: [[-60, -30], [30, 60]]

  # 新增：彈跳幾次後加速
  speed_scale_every: 1
  speed_increment: 0.1

training:
  max_generations: 30        # 最多迭代幾代
  episodes_per_generation: 2000
  eval_episodes: 100         # 每代結束後評估
  win_threshold: 0.7        # 勝率 > 0.7 即升級
  max_retries_for_generation: 10

  lr: 0.0005
  gamma: 0.99
  batch_size: 128
  memory_size: 500000
  epsilon_decay: 0.997
  min_epsilon: 0.08

  init_model_path: "checkpoints/model2_gen0.pth"  # 一開始載入

  
