env:
  render_size: 400
  paddle_width: 0.2
  paddle_speed: 0.02
  max_score: 3
  enable_render: false

  # 馬格努斯 + 剛體參數
  enable_spin: true
  magnus_factor: 0.01
  restitution: 0.9
  friction: 0.2
  ball_mass: 1.0
  world_ball_radius: 0.03

  # 初始條件
  ball_speed_range: [0.01, 0.05]
  spin_range: [-10, 10]
  ball_angle_intervals: [[-60, -30], [30, 60]]

  # 新增：彈跳幾次後加速
  speed_scale_every: 3
  speed_increment: 0.2

training:
  max_generations: 10        # 最多迭代幾代
  episodes_per_generation: 500
  eval_episodes: 50         # 每代結束後評估
  win_threshold: 0.65        # 勝率 > 0.7 即升級

  lr: 0.0005
  gamma: 0.99
  batch_size: 64
  memory_size: 50000
  epsilon_decay: 0.995
  min_epsilon: 0.05

  init_model_path: "checkpoints/model_gen0.pth"  # 一開始載入
