env:
  render_size: 400
  paddle_width: 0.2
  paddle_speed: 0.03
  max_score: 3
  enable_render: false

  # 馬格努斯 + 剛體參數
  enable_spin: true
  magnus_factor: 0.015
  restitution: 1
  friction: 0.4
  ball_mass: 1.0
  world_ball_radius: 0.03

  # 初始條件
  ball_speed_range: [0.04, 0.06]
  spin_range: [-5, 5]
  ball_angle_intervals: [[-60, -30], [30, 60]]

  # 新增：彈跳幾次後加速
  speed_scale_every: 5
  speed_increment: 0.1

training:
  max_generations: 10        # 最多迭代幾代
  episodes_per_generation: 500
  eval_episodes: 50         # 每代結束後評估
  win_threshold: 0.65        # 勝率 > 0.7 即升級

  lr: 0.0005
  gamma: 0.99
  batch_size: 64
  memory_size: 50000
  epsilon_decay: 0.995
  min_epsilon: 0.05

  init_model_path: "checkpoints/model_gen0.pth"  # 一開始載入
